# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rate_scrapper_gui_1.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 516)
        MainWindow.setStyleSheet("QWidget#MainWindow{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(148, 202, 236, 255), stop:1 rgba(146, 153, 255, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(148, 202, 236, 255), stop:1 rgba(146, 153, 255, 255));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainLayout = QtWidgets.QGridLayout()
        self.mainLayout.setContentsMargins(10, 15, 10, 10)
        self.mainLayout.setSpacing(15)
        self.mainLayout.setObjectName("mainLayout")
        self.leftPanel = QtWidgets.QGridLayout()
        self.leftPanel.setVerticalSpacing(10)
        self.leftPanel.setObjectName("leftPanel")
        self.suggestedCurrenciesLabel = QtWidgets.QLabel(self.centralwidget)
        self.suggestedCurrenciesLabel.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 11pt \"Fixedsys\";\n"
"color: rgb(0, 0, 0);")
        self.suggestedCurrenciesLabel.setObjectName("suggestedCurrenciesLabel")
        self.leftPanel.addWidget(self.suggestedCurrenciesLabel, 0, 1, 1, 1)
        self.currencyAndCountriesField = QtWidgets.QTextEdit(self.centralwidget)
        self.currencyAndCountriesField.setMinimumSize(QtCore.QSize(200, 150))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.currencyAndCountriesField.setFont(font)
        self.currencyAndCountriesField.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(220, 222, 255);\n"
"font: 10pt \"Gill Sans MT\";")
        self.currencyAndCountriesField.setPlaceholderText("")
        self.currencyAndCountriesField.setObjectName("currencyAndCountriesField")
        self.leftPanel.addWidget(self.currencyAndCountriesField, 1, 0, 1, 1)
        self.currencyAndCountriesLabel = QtWidgets.QLabel(self.centralwidget)
        self.currencyAndCountriesLabel.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 11pt \"Fixedsys\";\n"
"color: rgb(0, 0, 0);")
        self.currencyAndCountriesLabel.setObjectName("currencyAndCountriesLabel")
        self.leftPanel.addWidget(self.currencyAndCountriesLabel, 0, 0, 1, 1)
        self.suggestedCurrenciesTable = QtWidgets.QTableWidget(self.centralwidget)
        self.suggestedCurrenciesTable.setEnabled(True)
        self.suggestedCurrenciesTable.setMinimumSize(QtCore.QSize(200, 150))
        self.suggestedCurrenciesTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.suggestedCurrenciesTable.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(220, 222, 255);\n"
"font: 10pt \"Gill Sans MT\";")
        self.suggestedCurrenciesTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.suggestedCurrenciesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.suggestedCurrenciesTable.setDragDropOverwriteMode(False)
        self.suggestedCurrenciesTable.setAlternatingRowColors(False)
        self.suggestedCurrenciesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.suggestedCurrenciesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.suggestedCurrenciesTable.setColumnCount(1)
        self.suggestedCurrenciesTable.setObjectName("suggestedCurrenciesTable")
        self.suggestedCurrenciesTable.setRowCount(0)
        self.suggestedCurrenciesTable.horizontalHeader().setVisible(False)
        self.suggestedCurrenciesTable.horizontalHeader().setCascadingSectionResizes(True)
        self.suggestedCurrenciesTable.horizontalHeader().setDefaultSectionSize(200)
        self.suggestedCurrenciesTable.horizontalHeader().setMinimumSectionSize(200)
        self.suggestedCurrenciesTable.horizontalHeader().setSortIndicatorShown(True)
        self.suggestedCurrenciesTable.horizontalHeader().setStretchLastSection(True)
        self.suggestedCurrenciesTable.verticalHeader().setVisible(False)
        self.suggestedCurrenciesTable.verticalHeader().setCascadingSectionResizes(True)
        self.suggestedCurrenciesTable.verticalHeader().setDefaultSectionSize(20)
        self.suggestedCurrenciesTable.verticalHeader().setHighlightSections(False)
        self.suggestedCurrenciesTable.verticalHeader().setMinimumSectionSize(20)
        self.suggestedCurrenciesTable.verticalHeader().setSortIndicatorShown(True)
        self.suggestedCurrenciesTable.verticalHeader().setStretchLastSection(True)
        self.leftPanel.addWidget(self.suggestedCurrenciesTable, 1, 1, 1, 1)
        self.reportFileDirectoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.reportFileDirectoryLabel.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 11pt \"Fixedsys\";\n"
"color: rgb(0, 0, 0);")
        self.reportFileDirectoryLabel.setObjectName("reportFileDirectoryLabel")
        self.leftPanel.addWidget(self.reportFileDirectoryLabel, 2, 0, 1, 1)
        self.progressLabel = QtWidgets.QLabel(self.centralwidget)
        self.progressLabel.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 11pt \"Fixedsys\";\n"
"color: rgb(0, 0, 0);")
        self.progressLabel.setObjectName("progressLabel")
        self.leftPanel.addWidget(self.progressLabel, 4, 0, 1, 1)
        self.reportFileDirectoryField = QtWidgets.QLineEdit(self.centralwidget)
        self.reportFileDirectoryField.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(220, 222, 255);\n"
"height: 20px;\n"
"font: 10pt \"Gill Sans MT\";")
        self.reportFileDirectoryField.setReadOnly(True)
        self.reportFileDirectoryField.setObjectName("reportFileDirectoryField")
        self.leftPanel.addWidget(self.reportFileDirectoryField, 3, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    background-color: rgb(220, 222, 255);\n"
"    height: 20px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius:5px;    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.006, x2:1, y2:0, stop:0.193182 rgba(0, 135, 182, 255), stop:0.892045 rgba(0, 223, 255, 255));    \n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.leftPanel.addWidget(self.progressBar, 5, 0, 1, 2)
        self.mainLayout.addLayout(self.leftPanel, 1, 0, 1, 1)
        self.rightPanel = QtWidgets.QGridLayout()
        self.rightPanel.setObjectName("rightPanel")
        self.page_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_10.setEnabled(False)
        self.page_10.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_10.setObjectName("page_10")
        self.rightPanel.addWidget(self.page_10, 12, 0, 1, 1)
        self.page_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_9.setEnabled(False)
        self.page_9.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_9.setObjectName("page_9")
        self.rightPanel.addWidget(self.page_9, 11, 0, 1, 1)
        self.page_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_7.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_7.setChecked(True)
        self.page_7.setObjectName("page_7")
        self.rightPanel.addWidget(self.page_7, 7, 0, 1, 1)
        self.page_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_3.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_3.setChecked(True)
        self.page_3.setObjectName("page_3")
        self.rightPanel.addWidget(self.page_3, 3, 0, 1, 1)
        self.page_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_4.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_4.setChecked(True)
        self.page_4.setObjectName("page_4")
        self.rightPanel.addWidget(self.page_4, 4, 0, 1, 1)
        self.page_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_5.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_5.setChecked(True)
        self.page_5.setObjectName("page_5")
        self.rightPanel.addWidget(self.page_5, 5, 0, 1, 1)
        self.page_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_8.setEnabled(False)
        self.page_8.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_8.setObjectName("page_8")
        self.rightPanel.addWidget(self.page_8, 10, 0, 1, 1)
        self.transferPagesLabel = QtWidgets.QLabel(self.centralwidget)
        self.transferPagesLabel.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 11pt \"Fixedsys\";\n"
"color: rgb(0, 0, 0);")
        self.transferPagesLabel.setObjectName("transferPagesLabel")
        self.rightPanel.addWidget(self.transferPagesLabel, 0, 0, 1, 1)
        self.page_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_6.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_6.setChecked(True)
        self.page_6.setObjectName("page_6")
        self.rightPanel.addWidget(self.page_6, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rightPanel.addItem(spacerItem, 15, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setEnabled(True)
        self.browseButton.setMinimumSize(QtCore.QSize(120, 0))
        self.browseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browseButton.setStyleSheet("QPushButton {\n"
"border-color: rgb(170, 170, 0);\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius: 5px;\n"
"font: 75 11pt \"Fixedsys\";\n"
"color: rgb(255, 255, 255);\n"
"height: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(30, 125, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: white;\n"
"    background-color: rgb(198, 198, 198);\n"
"}")
        self.browseButton.setIconSize(QtCore.QSize(30, 30))
        self.browseButton.setCheckable(True)
        self.browseButton.setObjectName("browseButton")
        self.rightPanel.addWidget(self.browseButton, 14, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightPanel.addItem(spacerItem1, 13, 0, 1, 1)
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setEnabled(True)
        self.generateButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.generateButton.setFont(font)
        self.generateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generateButton.setMouseTracking(True)
        self.generateButton.setStyleSheet("QPushButton {\n"
"border-color: rgb(170, 170, 0);\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius: 5px;\n"
"font: 75 11pt \"Fixedsys\";\n"
"color: rgb(255, 255, 255);\n"
"height: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(0, 85, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: white;\n"
"    background-color: rgb(30, 125, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: white;\n"
"    background-color: rgb(198, 198, 198);\n"
"}")
        self.generateButton.setShortcut("")
        self.generateButton.setCheckable(True)
        self.generateButton.setObjectName("generateButton")
        self.rightPanel.addWidget(self.generateButton, 16, 0, 1, 1)
        self.page_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_1.setEnabled(False)
        self.page_1.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_1.setChecked(False)
        self.page_1.setObjectName("page_1")
        self.rightPanel.addWidget(self.page_1, 8, 0, 1, 1)
        self.page_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.page_2.setEnabled(False)
        self.page_2.setStyleSheet("border-color: rgb(170, 170, 0);\n"
"border-radius: 5px;\n"
"font: 75 10pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.page_2.setChecked(False)
        self.page_2.setObjectName("page_2")
        self.rightPanel.addWidget(self.page_2, 9, 0, 1, 1)
        self.mainLayout.addLayout(self.rightPanel, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.mainLayout, 1, 0, 1, 1)
        self.navigationPanel = QtWidgets.QFrame(self.centralwidget)
        self.navigationPanel.setStyleSheet("background-color: rgb(95, 95, 95);\n"
"font: 12pt \"Gill Sans MT\";")
        self.navigationPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigationPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigationPanel.setObjectName("navigationPanel")
        self.gridLayout = QtWidgets.QGridLayout(self.navigationPanel)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.closeButton = QtWidgets.QLabel(self.navigationPanel)
        self.closeButton.setStyleSheet("")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.maximizeButton = QtWidgets.QLabel(self.navigationPanel)
        self.maximizeButton.setStyleSheet("")
        self.maximizeButton.setObjectName("maximizeButton")
        self.gridLayout.addWidget(self.maximizeButton, 0, 4, 1, 1)
        self.minimizeButton = QtWidgets.QLabel(self.navigationPanel)
        self.minimizeButton.setStyleSheet("")
        self.minimizeButton.setObjectName("minimizeButton")
        self.gridLayout.addWidget(self.minimizeButton, 0, 3, 1, 1)
        self.appTitle = QtWidgets.QLabel(self.navigationPanel)
        self.appTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.appTitle.setObjectName("appTitle")
        self.gridLayout.addWidget(self.appTitle, 0, 1, 1, 1)
        self.appLogo = QtWidgets.QLabel(self.navigationPanel)
        self.appLogo.setObjectName("appLogo")
        self.gridLayout.addWidget(self.appLogo, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.navigationPanel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.generateButton.clicked['bool'].connect(MainWindow.setAnimated) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.suggestedCurrenciesLabel.setText(_translate("MainWindow", "All Currencies:"))
        self.currencyAndCountriesField.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gill Sans MT\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.currencyAndCountriesLabel.setText(_translate("MainWindow", "Currencies and Countries:"))
        self.suggestedCurrenciesTable.setSortingEnabled(True)
        self.reportFileDirectoryLabel.setText(_translate("MainWindow", "Report file Directory:"))
        self.progressLabel.setText(_translate("MainWindow", "Progress:"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.page_10.setText(_translate("MainWindow", "https://www.rewire.com/"))
        self.page_9.setText(_translate("MainWindow", "https://azimo.com/"))
        self.page_7.setText(_translate("MainWindow", "https://wise.com/"))
        self.page_3.setText(_translate("MainWindow", "https://www.instarem.com/"))
        self.page_4.setText(_translate("MainWindow", "https://app.currencyfair.com/"))
        self.page_5.setText(_translate("MainWindow", "https://my.transfergo.com/"))
        self.page_8.setText(_translate("MainWindow", "https://paysend.com/"))
        self.transferPagesLabel.setText(_translate("MainWindow", "Transfer Pages:"))
        self.page_6.setText(_translate("MainWindow", "https://secure.xendpay.com/"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.generateButton.setText(_translate("MainWindow", "Generate"))
        self.page_1.setText(_translate("MainWindow", "https://www.xoom.com/"))
        self.page_2.setText(_translate("MainWindow", "https://www.worldremit.com/"))
        self.closeButton.setText(_translate("MainWindow", "closeButton"))
        self.maximizeButton.setText(_translate("MainWindow", "maximizeButton"))
        self.minimizeButton.setText(_translate("MainWindow", "minimizeButton"))
        self.appTitle.setText(_translate("MainWindow", "Rate Scrapper"))
        self.appLogo.setText(_translate("MainWindow", "appLogo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
